targets:
  $default:
    sources:
      - lib/**
      - schema.graphql
    builders:
      artemis:
        options:
          schema_mapping:
            - schema: schema.graphql
              queries_glob: lib/graphql/*.graphql
              output: lib/graphql/graphql_api.dart